version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/simple-python-app/sources/
hooks:
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
